name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        echo "export const environment = {
          emailJsSeviceId: '${{ secrets.EMAILJS_SERVICE_ID }}',
          emailJsTemplateId: '${{ secrets.EMAILJS_TEMPLATE_ID }}',
          publicApikey: '${{ secrets.EMAILJS_PUBLIC_KEY }}',
          privateApiKey: '${{ secrets.EMAILJS_PRIVATE_KEY }}',
          formspreeEndpoint: '${{ secrets.FORMSPREE_ENDPOINT }}'
        };" > src/environments/environment.ts
        
    - name: Build
      run: npm run build --prod
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/Portafolio
